packages:
   - 'apps/*'
   - 'packages/*'

catalog:
   react: ^19.2.1
   '@types/react': ^19.2.7
   react-dom: ^19.2.1
   '@types/react-dom': ^19.2.3
   tailwindcss: ^4.1.17
   lucide-react: 0.561.0
   typescript: ^5.8.3
   '@types/node': ^20.11.17
